version: "3"

services:
  # Proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    links:
      - api
      - ui-elm
      - ui-polymer
      - monitor
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./configuration/nginx/conf.d/elm.dev.conf:/etc/nginx/conf.d/elm.dev.conf
      - ./configuration/nginx/conf.d/polymer.dev.conf:/etc/nginx/conf.d/polymer.dev.conf
      - ./elm-ui:/var/www/elm
      - ./polymer-ui:/var/www/polymer
    networks:
     - backend
     - frontend

  # Backend
  ## EXPRESS API
  api:
    image: kmade/api
    container_name: api
    depends_on:
      - db
    build: ./api
    command: yarn start:dev
    volumes:
      - ./api/:/app
      - /app/node_modules
    ports:
      - "4000:4000"
      - "5858:5858"
    networks:
     - backend
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: api.app.dev
      VIRTUAL_PORT: 4000
  ## DB
  db:
    image: kmade/db
    build: ./db
    container_name: db
    volumes:
      - ./db/etc:/usr/local/etc/couchdb/local.d
      - ./db/lib:/usr/local/var/lib/couchdb
    ports:
      - "5984:5984"
    networks:
      - frontend
    environment:
      NODE_ENV: development
      VIRTUAL_PORT: 5984
      VIRTUAL_HOST: db.app.dev
  ## bus
  bus:
    image: kmade/bus
    build: ./bus
    container_name: bus
    hostname: bus.app.dev
    ports:
      - 5000:5672
      - 15672::15672
    networks:
      - backend
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: bus.app.dev
      VIRTUAL_PORT: 5000
      VIRTUAL_PORT: 15672
  ## Monitoring
  monitor:
    image: kmade/monitor
    build: ./monitor
    container_name: monitor
    depends_on:
      - db
      - api
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - /var/lib/grafana
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: monitor.app.dev
      VIRTUAL_PORT: 3000
      GF_SERVER_ROOT_URL: http://monitor.app.dev
      GF_SECURITY_ADMIN_PASSWORD: secret
      #GF_PATHS_DATA: ./logs/data
      #GF_PATHS_LOGS: ./logs/monitor
  # Frontend
  ## Dashboard
  ui-elm:
    #restart: always
    image: kmade/ui-elm
    container_name: ui-elm
    build: ./elm-ui
    command: yarn build && yarn start:dev
    volumes:
      - ./elm-ui/:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - "8000:8000"
    networks:
      - frontend
    environment:
      NODE_ENV: development
      VIRTUAL_PORT: 8000
  ui-polymer:
    #restart: always
    image: kmade/ui-polymer
    container_name: ui-polymer
    build: ./polymer-ui
    command: yarn build && yarn start:dev
    volumes:
      - ./polymer-ui/:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - frontend
    environment:
      NODE_ENV: development
      VIRTUAL_PORT: 8080
      VIRTUAL_PORT: 8081

networks:
  backend:
    driver: "bridge"
  frontend:
    driver: "bridge"
