version: "3.3"

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

services:
  app:
    networks:
      - frontend-net
    env_file:
      - ${ROOT_PATH}/.env
    build:
      context: ${APP_PATH}
    stdin_open: true
    tty: true
    command: npm run start:dev
    volumes:
      - ${APP_PATH}/:/usr/src/app
      - /usr/src/app/node_modules
  dashboard:
    networks:
      - frontend-net
    environment:
      - BASE_URL=dashboard
    env_file:
      - ${ROOT_PATH}/.env
    build:
      context: ${DASHBOARD_PATH}
    stdin_open: true
    tty: true
    command: npm run start:dev
    volumes:
      - ${DASHBOARD_PATH}/:/usr/src/app
      - /usr/src/app/node_modules
  api:
    depends_on:
      - service-http
    networks:
      - frontend-net
      - backend-net
    env_file:
      - ${ROOT_PATH}/.env
    build:
      context: ${API_PATH}
    command: npm run start:dev
    volumes:
      - ${API_PATH}/:/usr/src/app
      - /usr/src/app/node_modules

  service-http:
    networks:
      - backend-net
    env_file:
      - ${ROOT_PATH}/.env
    build:
      context: ${SERVICE_HTTP_PATH}
    command: npm run start:dev
    volumes:
      - ${SERVICE_HTTP_PATH}/:/usr/src/app
      - /usr/src/app/node_modules

  proxy:
    env_file:
      - ${ROOT_PATH}/.env
    depends_on:
      - app
      - dashboard
    build:
      context: ${ROOT_PATH}
    volumes:
      - ${CONF_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CONF_PATH}/ssl/:/etc/nginx/ssl
    networks:
      - frontend-net
    ports:
      - "80:80"
      - "443:443"