version: "3.3"

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}.nginx
    image: nginx:alpine

  app:
    container_name: ${COMPOSE_PROJECT_NAME}.app
    image: ${COMPOSE_PROJECT_NAME}.app

  api:
    container_name: ${COMPOSE_PROJECT_NAME}.api
    image: ${COMPOSE_PROJECT_NAME}.api

  service-http:
    container_name: ${COMPOSE_PROJECT_NAME}.service-http
    image: ${COMPOSE_PROJECT_NAME}.service-http