version: "3.3"

services:
  app:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NS}/app
    build:
      args:
        NODE_IMG: ${NODE_IMG}
        NODE_VERSION: ${NODE_VERSION}
  dashboard:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NS}/dashboard
    build:
      args:
        NODE_IMG: ${NODE_IMG}
        NODE_VERSION: ${NODE_VERSION}
  api:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NS}/api
    build:
      args:
        NODE_IMG: ${NODE_IMG}
        NODE_VERSION: ${NODE_VERSION}

  service-http:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NS}/service-http
    build:
      args:
        NODE_IMG: ${NODE_IMG}
        NODE_VERSION: ${NODE_VERSION}
  proxy:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NS}/proxy
    build:
      args:
        NGINX_IMG: ${NGINX_IMG}