version: "3.3"

services:
  app:
    build:
      context: ${APP_PATH}
      dockerfile: production.Dockerfile
      args:
        NODE_ENV: production
    command: /bin/true
  dashboard:
    build:
      context: ${DASHBOARD_PATH}
      dockerfile: production.Dockerfile
    command: /bin/true
  proxy:
    build:
      context: ${ROOT_PATH}
      dockerfile: production.Dockerfile
    volumes:
      - ${CONF_PATH}/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      #- ${CONF_PATH}/ssl/:/etc/nginx/ssl
