version: "3"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  ###############################
  # Proxy
  ###############################
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    links:
      - api
      - ui-elm
      - ui-polymer
      - db
      - docs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
     - backend
     - frontend
  # Backend
  ## api
  api:
    image: kmade/api
    container_name: api
    restart: unless-stopped
    depends_on:
      - db
    build: ${SERVICES_PATH}/api
    command: yarn start:dev
    volumes:
      - ${SERVICES_PATH}/api/:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 5858:5858
    networks:
     - backend
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: api.app.dev
      VIRTUAL_PORT: 4000
    labels:
      org.label-schema.group: "api"
  ## db
  db:
    restart: unless-stopped
    build: ${SERVICES_PATH}/db
    container_name: db
    volumes:
      - ${SERVICES_PATH}/db/etc:/usr/local/etc/couchdb/local.d
      - ${SERVICES_PATH}/db/lib:/usr/local/var/lib/couchdb
    ports:
      - 5984:5984
    networks:
      - backend
    environment:
      NODE_ENV: development
      VIRTUAL_PORT: 5984
      VIRTUAL_HOST: db.app.dev
    labels:
      org.label-schema.group: "db"
  ## bus
  bus:
    restart: unless-stopped
    build: ${SERVICES_PATH}/bus
    container_name: bus
    hostname: bus.app.dev
    ports:
      - 5672:5672
      - 15672::15672
    networks:
      - backend
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: bus.app.dev
      VIRTUAL_PORT: 5672
      VIRTUAL_PORT: 15672
    labels:
      org.label-schema.group: "bus"
  # Frontend
  ## gui
  ui-elm:
    restart: unless-stopped
    image: kmade/ui-elm
    container_name: ui-elm
    build: ${SERVICES_PATH}/elm-ui
    command: yarn start:dev
    volumes:
      - ${SERVICES_PATH}/elm-ui/:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - 8000:8000
    networks:
      - frontend
    environment:
      NODE_ENV: development
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: elm.app.dev
    labels:
      org.label-schema.group: "ui"
  ui-polymer:
    restart: unless-stopped
    image: kmade/ui-polymer
    container_name: ui-polymer
    build: ${SERVICES_PATH}/polymer-ui
    command: yarn start:dev
    volumes:
      - ${SERVICES_PATH}/polymer-ui/:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - frontend
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: polymer.app.dev
      VIRTUAL_PORT: 8080
      VIRTUAL_PORT: 8081
    labels:
      org.label-schema.group: "ui"
  ## documentation
  docs:
    restart: unless-stopped
    container_name: docs
    build: ${SERVICES_PATH}/docs
    command: yarn start:dev
    volumes:
      - ${SERVICES_PATH}/docs/:/app
      - /app/node_modules
    ports:
      - 4444:4444
    networks:
      - frontend
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: docs.app.dev
      VIRTUAL_PORT: 4444
    labels:
      org.label-schema.group: "docs"
