version: "3"

networks:
  monitor:
    driver: bridge
  logging:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  # Proxy
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    links:
      - log
      - monitor
      - alert
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
     - backend
     - frontend
     - logging
     - monitor

  ## Monitor and logging
  elasticsearch:
    build: ./services/logging/elasticsearch/
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - ./services/logging/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - logging
    labels:
      org.label-schema.group: "logging"

  logstash:
    restart: unless-stopped
    build: ./services/logging/logstash/
    container_name: logstash
    volumes:
      - ./services/logging/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./services/logging/logstash/pipeline:/usr/share/logstash/pipeline
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - logging
    depends_on:
      - elasticsearch
    labels:
      org.label-schema.group: "logging"

  log:
    build: ./services/logging/kibana/
    container_name: log
    restart: unless-stopped
    volumes:
      - ./services/logging/kibana/config/:/usr/share/kibana/config
    expose:
      - 5601
    ports:
      - 5601:5601
    networks:
      - logging
    depends_on:
      - elasticsearch
    environment:
      VIRTUAL_HOST: log.app.dev
      VIRTUAL_PORT: 5601

    labels:
      org.label-schema.group: "logging"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./services/monitor/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alert.app.dev'
      - '-storage.local.memory-chunks=100000'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor
    labels:
      org.label-schema.group: "monitoring"
  ###----------------------------------------###

  # cadvisor:
  #   image: google/cadvisor:latest
  #   container_name: cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   restart: unless-stopped
  #   expose:
  #     - 9000
  #   networks:
  #     - monitor
  #   labels:
  #     org.label-schema.group: "monitoring"

  monitor:
    restart: unless-stopped
    image: grafana/grafana
    container_name: monitor
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./configuration/grafana/user.config.env
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - monitor
    labels:
      org.label-schema.group: "monitoring"
    environment:
      VIRTUAL_HOST: monitor.app.dev
      VIRTUAL_PORT: 3000

  alert:
    restart: unless-stopped
    image: prom/alertmanager
    container_name: alert
    volumes:
      - ./services/monitor/alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    ports:
      - 9093:9093
    networks:
      - monitor
    labels:
      org.label-schema.group: "monitoring"
    environment:
      VIRTUAL_HOST: alert.app.dev
      VIRTUAL_PORT: 9093
