version: "3.3"

services:
  api:
    image: ${IMAGE_REGISTRY}/${COMPOSE_PROJECT_NS}/arm32v6.api
    build:
      context: ${API_PATH}
      args:
        NODE_IMG: arm32v6/node
        NODE_VERSION: 9-alpine

  service-http:
    image: ${IMAGE_REGISTRY}/${COMPOSE_PROJECT_NS}/arm32v6.service-http
    build:
      context: ${SERVICE_HTTP_PATH}
      args:
        NODE_IMG: arm32v6/node
        NODE_VERSION: 9-alpine

  proxy:
    image: ${IMAGE_REGISTRY}/${COMPOSE_PROJECT_NS}/arm32v7.proxy
    build:
      context: ${ROOT_PATH}
      args:
        NGINX_IMG: arm32v7/nginx