
version: "3.3"
networks:
  swarm-overlay:
    external: true

services:
  swarm-proxy:
    environment:
      - MODE=swarm
      - LISTENER_ADDRESS=swarm-listener
      - SERVICE_NAME=swarm-proxy
    image: ahaurw01/docker-flow-proxy:armhf
    networks:
      - swarm-overlay
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
  swarm-listener:
    image: ahaurw01/docker-flow-swarm-listener:armhf
    networks:
      - swarm-overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://swarm-proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://swarm-proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
  ssl:
    image: ahaurw01/docker-flow-letsencrypt:armhf
    networks:
      - swarm-overlay
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /hdd/kmade/volumes/logs/letsencrypt/:/var/log/letsencrypt/
    environment:
      - com.df.aclName=__acme_letsencrypt_companion # arbitrary aclName to make sure it's on top on HAProxy's list
      - DOMAIN_1=kmade.net
      - DOMAIN_2=('admin.kmade.net' 'status.kmade.net' 'registry.kmade.net' 'academy.kmade.net' 'sinergy.kmade.net')
      - CERTBOT_EMAIL=oancea.dragosh@gmail.com
      - PROXY_ADDRESS=swarm-proxy
      - CERTBOT_CRON_RENEW='10 15 * * *'
      - CERTBOTMODE=staging
    deploy:
      labels:
        com.df.servicePath: "/.well-known/acme-challenge"
        com.df.distribute: "true"
        com.df.notify: "true"
        com.df.port: 80
      replicas: 1
      placement:
        constraints:
          - node.role==manager
