version: "3.3"
networks:
  swarm-overlay:
    external: true

secrets:
  admin-pass:
    file: /hdd/kmade/configuration/secrets/admin-pass

services:
  status:
    image: alexellis2/visualizer-arm
    networks:
      - swarm-overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      labels:
        com.df.serviceDomain: "status.kmade.net"
        com.df.notify: "true"
        #com.df.httpOnly: "true"
        com.df.distribute: "true"
        com.df.port: 8080
  portainer:
    image: portainer/portainer:arm
    networks:
      - swarm-overlay
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    #command: --admin-password-file "/run/secrets/admin-pass -H unix:///var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      labels:
        com.df.serviceDomain: "admin.kmade.net"
        com.df.notify: "true"
        #com.df.httpOnly: "true"
        com.df.distribute: "true"
        com.df.port: 9000

