
version: "3.3"
networks:
  frontend-net:
      driver: overlay
  backend-net:
      driver: overlay
  swarm-overlay:
    external: true

services:
  nginx:
    image: arm32v7/nginx
    networks:
      - swarm-overlay
      - frontend-net
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - /hdd/kmade/configuration/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /hdd/kmade/configuration/ssl/:/etc/nginx/ssl
    deploy:
      replicas: 1
      labels:
        com.df.serviceDomain: "kmade.net"
        com.df.notify: "true"
        com.df.httpsOnly: "false"
        com.df.distribute: "true"
        com.df.servicePath: "/"
        com.df.addReqHeader: "X-Forwarded-For %[src]"
        com.df.port: 80
      placement:
        constraints:
          - node.role==manager
  app:
    image: kmade/arm32v6.app
    networks:
      - frontend-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    command: npm run start:dev
  api:
    image: kmade/arm32v6.api
    networks:
      - frontend-net
      - backend-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == p1
      restart_policy:
        condition: any
  service-http:
    networks:
      - backend-net
    image: kmade/arm32v6.service-http
    deploy:
      replicas: 1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == p2
      restart_policy:
        condition: any
