version: "3.3"

services:
  api:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NS}/api.arm32v6:${TAG:-latest}
    build:
      context: ${API_PATH}
      args:
        NODE_IMG: arm32v6/node
        NODE_VERSION: 9-alpine

  service-http:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NS}/service-http.arm32v6:${TAG:-latest}
    build:
      context: ${SERVICE_HTTP_PATH}
      args:
        NODE_IMG: arm32v6/node
        NODE_VERSION: 9-alpine

  proxy:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NS}/proxy.arm32v7:${TAG:-latest}
    build:
      context: ${ROOT_PATH}
      args:
        NGINX_IMG: arm32v7/nginx